# Generated by Django 5.0.7 on 2024-09-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                ("role", models.CharField(max_length=50)),
                ("contactInfo", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("journalID", models.AutoField(primary_key=True, serialize=False)),
                ("entries", models.TextField()),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="core.user",
                    ),
                ),
                ("adminID", models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="core.user",
                    ),
                ),
                ("mentorID", models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("sessionID", models.AutoField(primary_key=True, serialize=False)),
                ("sessionName", models.CharField(max_length=150)),
                ("sessionStatus", models.CharField(max_length=50)),
                ("participants", models.ManyToManyField(to="core.user")),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("contentID", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.admin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="core.user",
                    ),
                ),
                ("studentID", models.AutoField(primary_key=True, serialize=False)),
                ("placementInfo", models.TextField()),
                (
                    "journalEntries",
                    models.ManyToManyField(related_name="students", to="core.journal"),
                ),
                (
                    "mentorID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.mentor",
                    ),
                ),
            ],
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="Monitoring",
            fields=[
                ("monitoringID", models.AutoField(primary_key=True, serialize=False)),
                ("feedback", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "mentorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.mentor"
                    ),
                ),
                (
                    "studentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mentor",
            name="students",
            field=models.ManyToManyField(related_name="mentors", to="core.student"),
        ),
        migrations.AddField(
            model_name="journal",
            name="studentID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.student"
            ),
        ),
    ]
